[package]
name = "day09"
version = "0.1.0"
authors = ["Isaac Slavitt <isaac.slavitt@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"

[lib]
name = "intcode"
path = "src/intcode.rs"

[[bin]]
name = "day09"
path = "src/main.rs"
